### ISSUE TITLE
必要なAPI洗い出し

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-api#10]
随時追加。
- APIのI/OはWikiに書く
- [QiitaのDoc](https://qiita.com/api/v2/docs)が綺麗なので参考にする

**Comment by fukuiretu** [comment]
- [x] サインイン(Twitter, Facebook)
- [x] サインアウト
- [x] グループ作成
- [x] グループ編集
- [x] グループ一覧取得
- [x] グループへの招待
- [x] トピック作成
- [x] トピック編集
- [x] トピック一覧取得
- [x] ネタ作成
- [x] ネタ編集
- [x] ネタ一覧取得
- [x] イイね
- [x] イイね一覧
- [x] 一休さんに訊こう
- [x] プロフィール表示
- [x] プロフィール編集
- [x] 表示用ID(profiles.display_id)使用可チェック

**Comment by fukuiretu** [comment]
@ushisantoasobu とりあえず思いつく範囲で列挙してみました、添削よろしくー :bow:

**Comment by ushisantoasobu** [comment]
- [ ] イイね一覧

**Comment by ushisantoasobu** [comment]
もしかしたら・・・
- [ ] 一休さんに訊こう

**Comment by fukuiretu** [comment]
- [ ] プロフィール編集

**Comment by ushisantoasobu** [comment]
#### memo
- ソートはフロント側で
- 1トピックにつき100ネタまで
- ネタの投稿文字数上限140字

**Comment by ushisantoasobu** [comment]
@fukuiretu 
Ideaモデルにアイデア作成者の名前表示したいと思うので欲しいかも
あとスキのトータル数も欲しいかもです。

**Comment by fukuiretu** [comment]
@ushisantoasobu りょうかいっす！

**Comment by fukuiretu** [comment]
足りないAPIは別個にissue切るのでこちらはクローズ
