### ISSUE TITLE
色を決めたらcolors.ymlに正式なもの書く

### ISSUE THREAD

**Issue by ushisantoasobu** [sekainohajimari/ikyusan-api#146]
https://github.com/sekainohajimari/ikyusan-api/blob/master/db/fixtures/colors.yml#L13

**Comment by fukuiretu** [comment]
いかに変更になりました
https://github.com/sekainohajimari/ikyusan-api/blob/master/db/fixtures/color_codes.yml

**Comment by ushisantoasobu** [comment]
ここ、色情報自体 (RGB)はフロントでいまもっちゃうもっちゃう形になっていますが・・・closeします
