### ISSUE TITLE
アイディア関連のテーブル設計

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-api#15]

**Comment by fukuiretu** [comment]
テーブル名
- ideas

必要なカラム
- トピックID
- アイディア投稿者ユーザーID
- アイディア内容
- 匿名フラグ

**Comment by fukuiretu** [comment]
テーブル名
- likes

必要なカラム
- アイディアID
- likeユーザーID
- num

**Comment by ushisantoasobu** [comment]
likesテーブルはそのユーザが何個スキしたかも必要？

**Comment by fukuiretu** [comment]
おー、忘れてた！あざす！

**Comment by fukuiretu** [comment]
- rails g model idea references:topic poster_id:integer content:string anonymity:integer
- rails g model like references:idea liker_id:integer num:integer
