### ISSUE TITLE
アイコンをデフォルトに切り替えるAPIの追加

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-api#150]
ushisanから

```
アイコンをデフォルトにする、という機能ある？？twitterの画像使いたくない、みたいな。
```
- APIの用意
- デフォルトアイコン画像の用意
- アイコンをs3に設置

**Comment by fukuiretu** [comment]
@ushisantoasobu 対応してデプロイしました！ざっくり仕様説明すると、
- profilesテーブルに`in_use_default_icon(true/false)`というカラムを追加しました。`GET /api/v1/profile`でレスポンンスに含めるようにしたので、デフォルトiconに切り替えるボタン?の出しわけに利用してください。
- デフォルトiconに切り替えるAPIは`PUT /api/v1/profile/default_icon`です。このAPIで`profiles.icon_url`を`デフォルトのicon_url`(s3に仮で適当な画像置きました)に、`profiles.in_use_default_icon`を`true`に更新かけます。
- APIの仕様は https://github.com/sekainohajimari/ikyusan-api/blob/master/doc/api/v1/profile_controller.md みてください

そいでは、もろもろ確認おなしゃす:bow:

**Comment by ushisantoasobu** [comment]
問題なかったのでcloseします
