### ISSUE TITLE
notification取得APIへの仕様追加

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-api#154]
-  タイプをレスポンスに追加
- ページング

**Comment by fukuiretu** [comment]
@ushisantoasobu 対応したので確認おなしゃす:bow:

doc: https://github.com/sekainohajimari/ikyusan-api/blob/master/doc/api/v1/notification_controller.md

**Comment by ushisantoasobu** [comment]
フロント側も対応したのでcloseします
