### ISSUE TITLE
APIのHTTPメソッドを見直す

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-api#163]
before
- GET /api/v1/g/:id/edit
- GET /api/v1/g/:group_id/t/:id/edit
- GET /api/v1/profile/edit

after
- PATCH /api/v1/g/:id
- PATCH /api/v1/g/:group_id/t/:id
- PATCH /api/v1/profile

**Comment by fukuiretu** [comment]
@ushisantoasobu 変更しちゃいました、ひまなときに確認お願いします:bow:

**Comment by ushisantoasobu** [comment]
フロント側も対応したのでcloseします
